### ISSUE TITLE
Breakage on first usage: project template creation fails

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites-6#262]
Wow, the first two minutes with Foundation 6 are thrilling me. Are you really sure this is ready for a public beta? 

```

? What are you building today? A website (Foundation for Sites)
? What's the project called? f6-test
? Which template would you like to use? Advanced: includes a static site generator, and Sass/JS compilers

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/


Downloading the project template.../home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14
  chdir.call(process, d)
        ^
Error: ENOENT, no such file or directory
    at Error (native)
    at process.chdir (/home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:18:9)
    at process.chdir (/home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
    at /home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/lib/commands/new.js:84:15
    at ChildProcess.<anonymous> (/home/xxx/App/nodejs/npm/lib/node_modules/foundation-cli/node_modules/exec/exec.js:90:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)



```

**Comment by gakimball** [comment]
Just deployed a new version that fixes this. Run `npm install foundation-cli@beta --global` to get it.

**Comment by COLABORATI** [comment]
Great, thank you for the quick fix!
