### ISSUE TITLE
Error: Cannot find module 'mout'

### ISSUE THREAD

**Issue by holisticnetworking** [zurb/foundation-sites-6#303]
The same but different from this issue:
https://github.com/zurb/foundation-sites-6/issues/35?_pjax=%23js-repo-pjax-container

I'm running the new beta for the first time (had some permissions issues with npm, which I was able to work around with this link: https://docs.npmjs.com/getting-started/fixing-npm-permissions ). But now that Foundation was installed without using sudo, I'm getting the following error message:

ganymede:foundation-sites-6 tomb$ foundation
module.js:338
    throw err;
    ^

Error: Cannot find module 'mout'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tomb/npm-global/lib/node_modules/foundation-cli/node_modules/bower/lib/index.js:2:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by gakimball** [comment]
This is a tricky issue to diagnose, because the issue is with a dependency *within* a dependency of the CLI.

We published a final version of the CLI, 2.0.0, last week. Can you try installing it and see if the above error goes away? If you still have problems, open an issue on Foundation 6's permanent home, [zurb/foundation-sites](https://github.com/zurb/foundation-sites).
