### ISSUE TITLE
download error when customize component download

### ISSUE THREAD

**Issue by futurist** [zurb/foundation-sites-6#328]
When I unchecked flex-video, MotionUI component, and then click download, there's an error page as below:

http://foundation.zurb.com/sites/download/custom-f6

````
invalid data

TypeError: invalid data
    at WriteStream.Socket.write (net.js:617:11)
    at Object.execFileSync (child_process.js:459:20)
    at go (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/routes/index.js:302:18)
    at /home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/routes/index.js:374:8
    at Layer.handle [as handle_request] (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:176:3)
    at router (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:312:13)
    at /home/deployer/sites/node-foundation-customizer/node-foundation-customizer/app/node_modules/express/lib/router/index.js:280:7
````

**Comment by gakimball** [comment]
We deployed a new build of the customizer today. I tried unchecking the two components you mentioned (flex video and Motion UI), and the download worked fine.
